/**
 * user actions
 */

// USER SIGNUP
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE";

// USER SIGNIN
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAILURE = "USER_SIGNIN_FAILURE";

// USER APPLY FOR LOAN
export const USER_APPLY_FOR_LOAN_SUCCESS = "USER_APPLY_FOR_LOAN_SUCCESS";
export const USER_APPLY_FOR_LOAN_FAILURE = "USER_APPLY_FOR_LOAN_FAILURE";